#!/usr/bin/env python

NOUN                = 'tag-noun'
VERB                = 'tag-verb'
ARTICLE             = 'tag-article'
MODIFIER            = 'tag-modifier'
CONJUNCTION         = 'tag-conjunction'
PRONOUN             = 'tag-pronoun'
PREPOSITION         = 'tag-preposition'
PROPER_NOUN         = 'tag-proper noun'
NUMBER              = 'tag-number'
COMMA_SEMICOLON     = 'tag-comma or semicolon'
LEFT_PAREN          = 'tag-left parentheses'
RIGHT_PAREN         = 'tag-right parentheses'
NON_PUNC_CHAR       = 'tag-non punctuation character'
POSSESSIVE          = 'tag-possessive'
COLON_DASH          = 'tag-color or dash'
ABBREV              = 'tag-abbreviation'
ENDING_PUNC         = 'tag-sentence ending punctuation'
OTHERS              = 'tag-others'

IS_UPPER            = 'is_upper'
FOLLOWS_PUNC        = 'follows_punc'
